# Generated by Django 2.1.5 on 2019-03-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='deadline',
        ),
    ]
